language: node_js
node_js:
- 12.8.1
env:
- WEBPACK_VERSION=4 MOCHA_VERSION=4
- WEBPACK_VERSION=4 MOCHA_VERSION=5
cache: npm
install:
- npm install -g @vue/cli
- npm install -g @vue/cli-service-global
before_script:
- npm install webpack@$WEBPACK_VERSION
- npm install mocha@$MOCHA_VERSION
- yarn add @vue/cli-plugin-unit-mocha
script:
- yarn test:unit tests
before_deploy: vue build --target wc --name data-metrics-badge 'src/components/DataMetricsBadge.vue'
deploy:
  provider: npm
  email: kgarza@datacite.org
  api_key:
    secure: EHZ+qG1DB9VRS8Q1H43F+hjgxwxoIEPxbMz+3R5u/7/8gZss7L0FyyV9YO+h8a4ygHQNWbJAlhGRdhaXZQovURQSPwd53ClY/qvdsis/yv2T7J2ctImPobAUoFh9+HevkSk4ro0JghOhZPRY/8zpaaTIPeDhwEx4bw1ermndhugaLdO0qXtCof0kp2Z3mY0ZGPpkVMLoHXpWryfOMZgY+7madF9LCSzyxYnSnLXQt/e9lj5791dwujNx5udXeZtPHso5WIMMsVopPA/VpFbUXD28QF2jAX6cWWwd+JWPirma4/pOCz2jhl6juZ4XwyqJ6WB+zEA/x8CjLX8cAc01NBS3r7cSw/Yqh1UF52ULvKu2CaUwONMymILAd+dSQU/km3c6Uy73tqMnGIQLrx7Yp4nkG/ypQgeSJJBob5cEo7ItxtVY85y35pDCrR+pUKUqBzmrYjpilleJ/2rk+nKoCO39ZeTsuM1l/Y7m64+qTH4YNN51zeVxR7JPCeCnGGbUQFGQT9aYi/u2pVEAgB0Dc0+rJetK3cugapFNpEUYaalJjab9Sfmky+2i1tUmrn0kuYA3BhzQKxXRWH33fcJIhsp1W75Nfp1JN71iXlqGL/lJGfoEi98fBpUPkyWAF9fWUFFgD7uxmgucbwOM7/+KL+L35GxkHQMtQJcXkfTboTk=
  on:
    branch: master
    repo: datacite/spitz
