language: node_js
node_js:
- '10'
cache: npm
install:
- npm install -g @vue/cli
- npm install -g @vue/cli-service-global
before_script:
- npm install webpack
- npm install mocha
- yarn add @vue/cli-plugin-unit-mocha
script:
- yarn test:unit tests
before_deploy: yarn build --target wc --name data-metrics-badge 'src/components/DataMetricsBadge.vue'
deploy:
  provider: npm
  email: kgarza@datacite.org
  skip_cleanup: true
  edge: true
  api_token:
    secure: Z6xeXwnZsWu4bR3woa+Fh0ELRaDJb+7l9BtdXTdevusk2A4A+djt43UwRzJCPlGzTE6IXSk0jbjoXYEDLwwgF73Hv72f9sZhxFIAe9nqUrATpkaELr+/K3zm6BnJxj114q7m1C+5cYxagj96/JtavjGq8L0NVyx5/WWjkN/uWTbQNcLiPHiO+liN6AqygAU62GSz0NPSTLxYtQrPvq4wicSTTTbxrMGxQR9QwwDQjrNeigT4kevtJqKn3uYncEEIYOsZZ0e6kk/vLTu8BHNm+TPchkFPJPIjUQ32B9yEBHqZ54RCZLY8pGfUtCHbHLos/NyeUi8nrt2h3qGrrwmqzMCk1Dj1ZAUyAnYPLefpGoQTrvF+/a/GSTVwvZHyq9/AmQvuX1XYdOBSTe36dYSguBPegIfaq7ZGY69WdZaNzmFGdxGbtGeqM8jOwVun2e4vFGRnYgIGwJjX3U10vXYDA6QI7jjEK2VcilMznQDsIpAu3w/DOY43bjkU476XorURMcd0UVH+5o7WgO4nQhhGiHzkJxlp/T8+JfDWAZEBMxi6zs7/sJSpsPEsq910hzM6DtMoDHwpIDj5CLN04ZwNRiVoR3QrkhV22nzFUv/AgM1jdfm5NCViHzamLdvWUnqHWc/ZTXebbrXntcV2q56GPPumAdYq3d50cLaH+Od9LEA=
  on:
    repo: datacite/spitz
    branch: master
  api_key:
    secure: jlj0FGhhoqhNxacqyIjrnTU7uneGvWLFs4emlR3ozhGtegREX8HXZC/zIsGzo3h9TffpjfHVlJRfe43y3Lam8yfbvJVJ50Ksv2bOERelObMZtyFyh+/TjGiApbYpuVy7k5ko1ScLFNVwOuHkq9Wh3ELxGQs3j7PIhAPY4x6q8KGyzTDB9hR2aW4yiSshtjzhpp1bOHmSi/obgTjHss/+GcN4HmXXEGZDVl1VDXkdTCruYESWlGHl02W7/cCEj/Gp4qMdAr3zL4Cy3z7f9dPZE89arLjShXsLhFxFZx70uHWkaDuEY1o0gBH+ScEPMX8//TixGYGVbFfGKwm1qMy+b8txWqW9oFv921ktAA4jn65wgqdPzeh6F4zvZteC+LU/4Aua7pI4RSi9wmBJMGOlrrZp2PCJntM0KO+O98OZowVKXngxRXhTJclppHrB453/rSrt2itMqwJopMeilpUAeIqQ+KHQ7l95Vn/9j1Z+rKtYuyyHf5k5IhASClpbFl/Yi2qcTas0+mhqIA4TPT+sRoP37pFKOPBloN8jKrFhIF/U7A4xTZHnE4J9soj+/QqKW2d5QOZI/wv4ocX+k63KITP9Xa7+z0Ys2+qJT5nwnEEtkXUEESynXoL1IvaR1owm6NzviMmZcAsozJxrhohDxNz859yMcWbWHxMP7Rr6YVg=
